FORMAT: 1A
HOST: http://www.google.com

# MOM
MOM API is a service to manage middleware of systems and its related devices.

#Group Systems
System related resources of the **Systems API**. You can create a system to start send and recieve from your linked devices.

## Systems Collection [/api/v1/systems{?code,name,user,status,fromDate,toDate,limit,offset}]
### List Systems [GET]
Error codes will be either:</br>
a) Wrong values for limit or offset</br>

+ Parameters
    + code (optional, string, `004`) ... Text `code` of the desired system(s).
    + name (optional, string, `system 1`) ... Text `name` of the desired system(s).
    + user (optional, string, `Mark`) ... Text `create user` of the desired system(s).
    + status (optional, number, `2`) ... Numeric `status` of the desired system(s). Lookup value.
    + fromDate (optional, string, `1-1-2014`) ... Date `from create date` of the desired system(s).
    + toDate (optional, string, `15-10-2014`) ... Date `to create date` of the desired system(s).
    + limit (optional, integer, `10`) ... Numeric `limit` of the desired record count or page size. Default 10
    + offset (optional, integer, `0`) ... Numeric `offset` of the desired offset of the data, where to start count. Default 0.

+ Request

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        [
            { 
                "code": "001", 
                "name": "system 1", 
                "user": "Tom", 
                "status": 2, 
                "createDate": "01-09-2014"
            }, 
            { 
                "code": "003",
                "name": "system xyz", 
                "user": "Mark", 
                "status": 1, 
                "createDate": "15-05-2014",
            }
        ]
        
+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E20", "messgae" : "error e20 description"}
            ]
        }
        
+ Response 401

## System [/api/v1/systems]
### Create a System [POST]
Calling this API will return a new system, with a **generated code** which will be used later.

Error codes will be either:</br>
a) Wrong format of Json</br>
b) Name is Required</br>
c) Name contains special characters</br>

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            { 
                "name": "adms", 
                "user": "John"
            }
        
+ Response 200 (application/json)

        { 
            "code": "002",
            "name": "adms", 
            "user": "John",
            "createDate": "15-05-2014",
            "status" : 1
        }
        
+ Response 400 (application/json)

        { "errors": [
                { "code": "E1", "message" : "error e1 description" },
                { "code": "E3", "message" : "error e3 description" }
            ]
        }

+ Response 401

## System [/api/v1/systems/{code}]
### Update a System [POST]
Error codes will be either:</br>
a) Wrong format of Json</br>
b) Name is Required</br>

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            { 
                "name": "adms", 
                "user": "John"
            }
        
+ Response 200 (application/json)

        { 
            "code": "002",
            "name": "adms", 
            "user": "John",
            "status" : 1,
            "createDate": "15-05-2014"
        }
        
+ Response 400 (application/json)

        { "errors": [
                { "code": "E1", "message" : "error e1 description" },
                { "code": "E3", "message" : "error e3 description" }
            ]
        }

+ Response 401

### Remove a System [DELETE]
+ Request

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        { 
            "code": "002",
            "name": "adms", 
            "user": "John",
            "status" : 2,
            "createDate": "15-05-2014"
        }

+ Response 400 (application/json)

        { "errors": [
                { "code": "E1", "message" : "error e1 description" },
                { "code": "E3", "message" : "error e3 description" }
            ]
        }

+ Response 401

## System [/api/v1/systems/delete/{code}]
### Remove a System [POST]
+ Request

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        { 
            "code": "002",
            "name": "adms", 
            "user": "John",
            "status" : 2,
            "createDate": "15-05-2014"
        }

+ Response 400 (application/json)

        { "errors": [
                { "code": "E1", "message" : "error e1 description" },
                { "code": "E3", "message" : "error e3 description" }
            ]
        }

+ Response 401

#Group Groups
Group related resources of the **Groups API**

## Groups Collection [/api/v1/groups{?code,name,user,systemCode,fromDate,toDate,limit,offset}]
### List Groups [GET]
Error codes will be either:</br>
a) Wrong values for limit or offset</br>

+ Parameters
    + code (optional, string, `004_g1`) ... Text `code` of the desired group(s).
    + name (optional, string, `group 1`) ... Text `name` of the desired group(s).
    + user (optional, string, `Mark`) ... Text `create user` of the desired group(s).
    + systemCode (optional, string, `020`) ... Text `system code` of the desired group(s).
    + fromDate (optional, string, `1-1-2014`) ... Date `from create date` of the desired group(s).
    + toDate (optional, string, `15-10-2014`) ... Date `to create date` of the desired group(s).
    + limit (optional, integer, `10`) ... Numeric `limit` of the desired record count or page size. Default 10
    + offset (optional, integer, `0`) ... Numeric `offset` of the desired offset of the data, where to start count. Default 0.

+ Request

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        [
            { 
                "code": "001_g2", 
                "name": "group 1", 
                "user": "Tom", 
                "system": {
                    "status":1,
                    "name":"System 1",
                    "code":"001",
                    "user":"Tom",
                    "createDate":"Tue Sep 09 15:40:23 EEST 2014"
                }, 
                "createDate": "01-09-2014"
            }, 
            { 
                "code": "021_g1",
                "name": "first floor", 
                "user": "Mark", 
                "system": {
                    "status":1,
                    "name":"System 12",
                    "code":"021",
                    "user":"Mark",
                    "createDate":"Tue Sep 09 15:40:23 EEST 2014"
                }, 
                "createDate": "15-05-2014",
            }
        ]
        
+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E20", "messgae" : "error e20 description"}
            ]
        }

+ Response 401

## Groups Collection [/api/v1/groups]
### Create a Group [POST]
Error codes will be either:</br>
a) Wrong format of Json</br>
b) Name is Required</br>
c) System Doesnt Exist</br>

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            { 
                "name": "first floor",
                "systemCode": "adms",
                "user": "John"
            }
        
+ Response 200 (application/json)

        {
            "code": "adms_g1",
            "name": "first floor", 
            "user": "John", 
            "system": {
                "status":1,
                "name":"ADMS System",
                "code":"adms",
                "user":"Mark",
                "createDate":"Tue Sep 09 15:40:23 EEST 2014"
            }, 
            "createDate": "15-05-2014",
        }

+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E1", "messgae" : "error e1 description"},
                {"code" : "E6", "messgae" : "error e6 description"}
            ]
        }

+ Response 401

## Group [/api/v1/groups/{code}]
### Update a Group [POST]
Error codes will be either:</br>
a) Wrong format of Json</br>
b) Name is Required</br>

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            { 
                "name": "secondFloorGP", 
                "user": "John"
            }
        
+ Response 200 (application/json)

        {
            "code": "adms_g1",
            "name": "secondFloorGP", 
            "user": "John", 
            "system": {
                "status":1,
                "name":"ADMS System",
                "code":"adms",
                "user":"Mark",
                "createDate":"Tue Sep 09 15:40:23 EEST 2014"
            }, 
            "createDate": "15-05-2014",
        }

+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E1", "messgae" : "error e1 description"},
                {"code" : "E6", "messgae" : "error e6 description"}
            ]
        }

+ Response 401

### Remove a Group [DELETE]
+ Request

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        {
            "code": "adms_g1",
            "name": "secondFloorGP", 
            "user": "John", 
            "system": {
                "status":1,
                "name":"ADMS System",
                "code":"adms",
                "user":"Mark",
                "createDate":"Tue Sep 09 15:40:23 EEST 2014"
            }, 
            "createDate": "15-05-2014",
        }

+ Response 400 (application/json)

        { "errors" : [
                {"code" : "E6", "messgae" : "error e6 description"}
            ]
        }

+ Response 401

## Group [/api/v1/groups/delete/{code}]
### Remove a Group [POST]
+ Request

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        {
            "code": "adms_g1",
            "name": "secondFloorGP", 
            "user": "John", 
            "system": {
                "status":1,
                "name":"ADMS System",
                "code":"adms",
                "user":"Mark",
                "createDate":"Tue Sep 09 15:40:23 EEST 2014"
            }, 
            "createDate": "15-05-2014",
        }

+ Response 400 (application/json)

        { "errors" : [
                {"code" : "E6", "messgae" : "error e6 description"}
            ]
        }

+ Response 401

#Group SystemDevices
Group related resources of the **SystemDevices API**

## SystemDevices Collection [/api/v1/systemDevices{?systemCode,sn,limit,offset}]
### List SystemDevices [GET]
Error codes will be either:</br>
a) Wrong values for limit or offset</br>

+ Parameters
    + systemCode (optional, string, `004`) ... Text `systemCode` of the desired system(s).
    + sn (optional, string, `5420318122`) ... Text `sn` is the serial number of desired device.
    + limit (optional, integer, `10`) ... Numeric `limit` of the desired record count or page size. Default 10
    + offset (optional, integer, `0`) ... Numeric `offset` of the desired offset of the data, where to start count. Default 0.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        [
            {
                "id": "12364",
                "system":{
                    "status": 1,
                    "name": "ADMS",
                    "code": "001",
                    "createDate": "Tue Sep 09 15:40:23 EEST 2014",
                    "user": "Mark"} 
                "sn": "12364974565", 
                "user": "Tom", 
                "status": 2, 
                "createDate": "01-09-2014"
            }, 
            {
                "id": "12365",
                "system":{
                    "status": 1,
                    "name": "ADMS",
                    "code": "001",
                    "createDate": "Tue Sep 09 15:40:23 EEST 2014",
                    "user": "Tom"
                }
                "sn": "123665415", 
                "user": "Mark", 
                "status": 1, 
                "createDate": "15-05-2014",
            }
        ]
        
+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E20", "messgae" : "error e20 description"}
            ]
        }

+ Response 401

## SystemDevice [/api/v1/systemDevices]
### Create a SystemDevice Link [POST]
Error codes will be either:</br>
a) Wrong format of Json</br>
b) Device Serial Number is Required</br>
c) System Doesnt Exist</br>

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body

            {
                "sn": "1203650",
                "systemCode": "002",
                "user": "John"
            }
        
+ Response 200 (application/json)

        {
            "id": "12362",
            "system":{
                "status": 1,
                "name": "ADMS",
                "code": "002",
                "createDate": "Tue Sep 09 15:40:23 EEST 2014",
                "user": "Tom"
            }
            "sn": "1203650", 
            "user": "John", 
            "status": 1, 
            "createDate": "15-05-2014",
        }

+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E7", "messgae" : "error e7 description"},
                {"code" : "E8", "messgae" : "error e8 description"}
            ]
        }

+ Response 401

## SystemDevice [/api/v1/systemDevices/{id}]
### Remove a systemDevices [DELETE]
+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        {
            "id": "12362",
            "system":{
                "status": 1,
                "name": "ADMS",
                "code": "002",
                "createDate": "Tue Sep 09 15:40:23 EEST 2014",
                "user": "Tom"
            }
            "sn": "1203650", 
            "user": "John", 
            "status": 1, 
            "createDate": "15-05-2014",
        }

+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E9", "messgae" : "error e9 description"}
            ]
        }

+ Response 401

## SystemDevice [/api/v1/systemDevices/delete/{id}]
### Remove a systemDevices [POST]
+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        {
            "id": "12362",
            "system":{
                "status": 1,
                "name": "ADMS",
                "code": "002",
                "createDate": "Tue Sep 09 15:40:23 EEST 2014",
                "user": "Tom"
            }
            "sn": "1203650", 
            "user": "John", 
            "status": 1, 
            "createDate": "15-05-2014",
        }

+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E9", "messgae" : "error e9 description"}
            ]
        }

+ Response 401    

#Group Group's Devices
Group related resources of the **Group's Devices API**

## Group Devices Collection [/api/v1/groupDevices{?groupCode,sn,limit,offset}]
### List group's devices given group code [GET]
Error codes will be either:</br>
a) Wrong values for limit or offset</br>

+ Parameters
    + groupCode (optional, string, `004_g1`) ... Text `groupCode` of the desired group(s).
    + sn (optional, string, `5420318122`) ... Text `sn` is the serial number of desired device.
    + limit (optional, integer, `10`) ... Numeric `limit` of the desired record count or page size. Default 10
    + offset (optional, integer, `0`) ... Numeric `offset` of the desired offset of the data, where to start count. Default 0.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        [
            { 
                "id": "12364",
                "group":{
                    "name":"ADMS g1",
                    "code":"004_g1",
                    "createDate":"Tue Nov 09 15:40:23 EEST 2014",
                    "user":"Mark",
                    "system":{
                        "status":1,
                        "name":"ADMS",
                        "code":"004",
                        "createDate":"Wed Nov 09 12:25:07 EET 2014",
                        "user":"Tom"
                    }
                } 
                "sn": "12364974565", 
                "user": "Tom", 
                "status": 2, 
                "createDate": "11-11-2014"
            }, 
            {
                "id": "12365",
                "group":{
                    "name":"ADMS g1",
                    "code":"004_g1",
                    "createDate":"Tue Nov 09 15:40:23 EEST 2014",
                    "user":"Mark",
                    "system":{
                        "status":1,
                        "name":"ADMS",
                        "code":"004",
                        "createDate":"Wed Nov 09 12:25:07 EET 2014",
                        "user":"Tom"
                    }
                }
                "sn": "123665415", 
                "user": "Mark", 
                "status": 1, 
                "createDate": "15-11-2014"
            }
        ]

+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E20", "messgae" : "error e20 description"}
            ]
        }

+ Response 401

## Group's Device [/api/v1/groupDevices]
### Create a link between group and device [POST]
Error codes will be either:</br>
a) Wrong format of JSON</br>
b) Device serial number is required</br>
c) Group does not exist</br>

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            { 
                "sn": "12365223",
                "groupCode": "004-g1",
                "user": "Mark"
            }
        
+ Response 200 (application/json)

        {
            "id": "12362",
            "group":{
                "name":"ADMS g1",
                "code":"004-g1",
                "createDate":"Tue Nov 09 15:40:23 EEST 2014",
                "user":"Mark",
                "system":{
                    "status":1,
                    "name":"ADMS",
                    "code":"004",
                    "createDate":"Wed Nov 09 12:25:07 EET 2014",
                    "user":"Tom"
                }
            }
            "sn": "12365223", 
            "user": "Mark", 
            "status": 1, 
            "createDate": "15-11-2014"
        }

+ Response 400 (application/json)

        { "errors" : [ 
                {"code" : "E7", "messgae" : "error e7 description"},
                {"code" : "E8", "messgae" : "error e8 description"}
            ]
        }

+ Response 401

## Group's Device [/api/v1/groupDevices/{id}]
### Remove a device from a group [DELETE]
+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        {
            "id": "12362",
            "group":{
                "name":"ADMS g1",
                "code":"004-g1",
                "createDate":"Tue Nov 09 15:40:23 EEST 2014",
                "user":"Mark",
                "system":{
                    "status":1,
                    "name":"ADMS",
                    "code":"004",
                    "createDate":"Wed Nov 09 12:25:07 EET 2014",
                    "user":"Tom"
                }
            }
            "sn": "12365223", 
            "user": "Mark", 
            "status": 1, 
            "createDate": "15-11-2014"
        }

+ Response 400 (application/json)

        { "errors" : [
                {"code" : "E9", "messgae" : "error e9 description"}
            ]
        }

+ Response 401

## Group's Device [/api/v1/groupDevices/delete/{id}]
### Remove a device from a group [POST]
+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

+ Response 200 (application/json)

        {
            "id": "12362",
            "group":{
                "name":"ADMS g1",
                "code":"004-g1",
                "createDate":"Tue Nov 09 15:40:23 EEST 2014",
                "user":"Mark",
                "system":{
                    "status":1,
                    "name":"ADMS",
                    "code":"004",
                    "createDate":"Wed Nov 09 12:25:07 EET 2014",
                    "user":"Tom"
                }
            }
            "sn": "12365223", 
            "user": "Mark", 
            "status": 1, 
            "createDate": "15-11-2014"
        }

+ Response 400 (application/json)

        { "errors" : [
                {"code" : "E9", "messgae" : "error e9 description"}
            ]
        }

+ Response 401

#Group OAUTH2
System related resources of the **OAUTH2 API**
## Access Token [/oauth2/token?grant_type=grant_type_value&client_id=<your_client_id>&client_secret=<your_client_secret>{&username,password,refresh_token}]
### get Access Token [POST]

+ Parameters
    + grant_type (required, string, `password or refresh_token`) ... Text `grant_type`.
    + client_id (required, string, `client_id`) ... Text `client_id`.
    + client_secret (required, string, `client_secret`) ... Text `client_secret`.
    + username (optional, string, `admin`) ... Text `username` required in case of grant type: password.
    + password (optional, string, `admin`) ... Text `password` required in case of grant type: password.
    + refresh_token (optional, string, `454as6fasasfjaosfa`) ... Text `refresh_token` required in case of grant type: refresh_token.
    
+ Request (application/x-www-form-urlencoded)

    
+ Response 200 (application/json)

        {"expires_in":3600,"token_type":"Bearer","refresh_token":"3b78cd275d7a31ac78c70e90150803bf","access_token":"e674b36f756567a042ad2d2177369958"}

+ Response 200 (application/json)

        {"expires_in":3600,"token_type":"Bearer","access_token":"5faaf4f574436a7955149f451ba778b4"}

+ Response 401



<!--
# Multi Collection

## SystemDevice [/api/v1/multi/systemDevices]
### Create multiple links between system and given devices [POST]
Error codes will be either:</br>
a) Wrong format of JSON</br>
b) Device serial number is required</br>
c) System does not exist</br>

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            [{ "sn": "12365",
              "systemCode": "004_g1",
              "user": "Mark"
            },
            { "sn": "32140",
              "systemCode": "004_g1",
              "user": "Mark"
            }]
        
+ Response 200 (application/json)

        [{ "id": "19",
           "sn": "12365",
           "systemCode": "004_g1",
           "user": "Mark"
        },
        { "id": "20",
           "sn": "32140",
           "systemCode": "004_g1",
           "user": "Mark"
        }] 

+ Response 400 (application/json)

        [{ "id": "19",
           "sn": "12365",
           "systemCode": "004_g1",
           "user": "Mark"
        },
        { "id": "-1",
           "sn": "32140",
           "systemCode": "004_g1",
           "user": "Mark",
           "errors" : [ 
                {"code" : "E7", "messgae" : "error e7 description"},
                {"code" : "E8", "messgae" : "error e8 description"}
            ]
        }] 

+ Response 401


## SystemDevice Device [/api/v1/multi/systemDevices/delete]
### Remove multiple devices links between its system [POST]
+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            [{ "id": "19"},{"id": "20"}]

+ Response 200 (application/json)

        [{ "id": "19"},{"id": "20"}] 

+ Response 400 (application/json)

        [
            {
                "id": "19"
            },
            {
                "id": "20", 
                "errors" : [
                    {"code" : "E6", "messgae" : "error e6 description"}
                ]
            }
        ]

+ Response 401


## Group's Device [/api/v1/multi/groupDevices]
### Create multiple links between group and given devices [POST]
Error codes will be either:</br>
a) Wrong format of JSON</br>
b) Device serial number is required</br>
c) Group does not exist</br>

+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            [{ "sn": "12365",
              "groupCode": "004_g1",
              "user": "Mark"
            },
            { "sn": "32140",
              "groupCode": "004_g1",
              "user": "Mark"
            }]
        
+ Response 200 (application/json)

        [{ "id": "19",
           "sn": "12365",
           "groupCode": "004_g1",
           "user": "Mark"
        },
        { "id": "20",
           "sn": "32140",
           "groupCode": "004_g1",
           "user": "Mark"
        }]

+ Response 400 (application/json)

        [{ "id": "19",
           "sn": "12365",
           "groupCode": "004_g1",
           "user": "Mark"
        },
        { "id": "-1",
           "sn": "32140",
           "groupCode": "004_g1",
           "user": "Mark",
           "errors" : [ 
                {"code" : "E7", "messgae" : "error e7 description"},
                {"code" : "E8", "messgae" : "error e8 description"}
            ]
        }]

+ Response 401


## Group's Device [/api/v1/multi/groupDevices/delete]
### Remove multiple devices links between its group [POST]
+ Request (application/json)

    + Headers
    
            Authorization: Bearer [TOKEN]

    + Body
    
            [{ "id": "19"},{"id": "20"}]

+ Response 200 (application/json)

        [{ "id": "19"},{"id": "20"}]  

+ Response 400 (application/json)

        [
            { 
                "id": "19"
            },
            {
                "id": "20",
                "errors" : [ 
                    {"code" : "E1", "messgae" : "error e1 description"},
                    {"code" : "E6", "messgae" : "error e6 description"}
                ]
            }
        ]

+ Response 401
-->


