FORMAT: 1A
HOST: http://www.google.com

# MOM
MOM API is a service similar to its physical paper presence on your table.

## Systems Collection [/apis/systems]
### Create a System [POST]
Error codes will be either:</br>
a) Wrong format of Json</br>
b) Name is Required</br>

+ Request (application/json)

        { "name": "adms", 
          "user": "John"
        }
        
+ Response 201 (application/json)

        { "code": "002" 
        }
        
+ Response 400 (application/json)

        [
            { "errorCode": "1" },
            { "errorCode": "6" }
        ]

## System [/systems/{code}]
### Update a System [POST]
Error codes will be either:</br>
a) Wrong format of Json</br>
b) Name is Required</br>

+ Request (application/json)

        { "name": "adms", 
          "user": "John"
        }
        
+ Response 200

        
+ Response 400 (application/json)

        [
            { "errorCode": "1" },
            { "errorCode": "6" }
        ]